# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bow' do
  use_frameworks!
  pod 'RxSwift'
  pod 'JSONCodable'
  pod 'HexColors'
  pod 'GuitarDsp', :path => '../GuitarDsp'
  pod 'EZAudio', :path => '../EZAudio'
  pod 'GuitarMidi', :path => '../GuitarMidi'
  pod 'CubicBezier', :path => '../CubicBezier'
  pod 'Beethoven', :git => 'https://github.com/MaciejMCh/Beethoven.git', :branch => 'osx'
  pod 'MIDIKit', :git => 'https://github.com/MaciejMCh/MIDIKit.git'
end
