# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace '../GuitarDsp.xcworkspace'

target 'Bow' do
  use_frameworks!
  pod 'RxSwift'
  pod 'JSONCodable'
  pod 'HexColors'

end
