# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuitarDsp' do
  use_frameworks!
  pod 'EZAudio', :path => '../EZAudio'
end

target 'GuitarDspIos' do
    use_frameworks!
    pod 'Novocaine', :path => '../novocaine'
end
