# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NodesMap iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NodesMap iOS

end

target 'NodesMap macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Mantle'
  # Pods for NodesMap macOS

end

target 'NodesMap tvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NodesMap tvOS

end

target 'NodesMap watchOS App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NodesMap watchOS App

end

target 'NodesMap watchOS App Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NodesMap watchOS App Extension

end
