# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace '../GuitarDsp.xcworkspace'

target 'GuitarMidi' do
  use_frameworks!
  pod 'Beethoven', :git => 'https://github.com/MaciejMCh/Beethoven.git'
  pod 'MIDIKit', :git => 'https://github.com/MaciejMCh/MIDIKit.git'

end
