# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
  use_frameworks!
  pod 'Beethoven', :git => 'https://github.com/MaciejMCh/Beethoven.git', :branch => 'osx'
  pod 'MIDIKit', :git => 'https://github.com/MaciejMCh/MIDIKit.git'
  pod 'GuitarDsp', :path => '../GuitarDsp'
  pod 'EZAudio', :path => '../EZAudio'
  pod 'CubicBezier', :path => '../CubicBezier'
  pod 'NodesMap', :path => '../NodesMap'
  pod 'JSONCodable'
end

target 'GuitarMidi' do
   pods
end

target 'WaveMapCreator' do
    use_frameworks!
    pod 'NodesMap', :path => '../NodesMap'
    pod 'GuitarDsp', :path => '../GuitarDsp'
    pod 'Beethoven', :git => 'https://github.com/MaciejMCh/Beethoven.git', :branch => 'osx'
    pod 'Novocaine', :path => '../novocaine'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'JSONCodable'
end
